name: bcsports_mobile
description: "BCSports"

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^2.24.2
  firebase_auth: ^4.17.3
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  firebase_database: ^10.4.4
  firebase_database_platform_interface: ^0.2.5+20
  cloud_firestore: ^4.15.3
  firebase_storage: ^11.6.5

  crypto: ^3.0.3

  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
  uuid: ^4.3.3
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  image_cropper: ^5.0.0

  sliver_tools: ^0.2.5
  google_fonts: ^6.1.0
  flutter_svg: any
  flutter_switch: ^0.3.2
  pinput: ^3.0.1
  photo_view: ^0.14.0

  intl: ^0.19.0

  flutter_native_splash: ^2.3.10
  flutter_chat_ui: ^1.6.12
  flutter_firebase_chat_core: ^1.6.7
  flutter_chat_types: ^3.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21


flutter:

  uses-material-design: true
  assets:
    - assets/images/onboarding/
    - assets/images/profile/
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#000000"
  image: "assets/images/logo.png"
  android_12:
    color: "#000000"