name: bcsports_mobile
description: "BCSports"

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^2.24.2
  firebase_auth: ^4.17.3
  google_sign_in: ^6.2.1
  firebase_database: ^10.4.4
  firebase_database_platform_interface: ^0.2.5+20
  cloud_firestore: ^4.15.3
  firebase_storage: ^11.6.5

  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7

  sliver_tools: ^0.2.5
  google_fonts: ^6.1.0
  flutter_svg: any
  flutter_switch: ^0.3.2
  pinput: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/profile/
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: HN
  #     fonts:
  #       - asset: assets/fonts/Helvetica-Neue/base.ttf
  #       - asset: assets/fonts/Helvetica-Neue/base-italic.otf
  #         style: italic
  #         weight: 500
  #       - asset: assets/fonts/Helvetica-Neue/zero.otf
  #         weight: 300
  #       - asset: assets/fonts/Helvetica-Neue/bold-italic.otf
  #         style: italic
  #         weight: 600
  #       - asset: assets/fonts/Helvetica-Neue/bold-x2-italic.otf
  #         style: italic
  #         weight: 700
  #       - asset: assets/fonts/Helvetica-Neue/bold-x3-italic.otf
  #         style: italic
  #         weight: 900