// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkBZ6eRSGvpfH1DJBgRGHlSDwVfViXvAA',
    appId: '1:626741015:android:f8c5fd1e9bbb10e020b152',
    messagingSenderId: '626741015',
    projectId: 'bcsports-mobile',
    databaseURL: 'https://bcsports-mobile-default-rtdb.firebaseio.com',
    storageBucket: 'bcsports-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Ni7eCvOjwPRFK-8W_rml9dxERkNjv-8',
    appId: '1:626741015:ios:719e19333b3a2cb620b152',
    messagingSenderId: '626741015',
    projectId: 'bcsports-mobile',
    databaseURL: 'https://bcsports-mobile-default-rtdb.firebaseio.com',
    storageBucket: 'bcsports-mobile.appspot.com',
    androidClientId: '626741015-1e68a6kc5g8b97qo3dk6egll1s77bs42.apps.googleusercontent.com',
    iosClientId: '626741015-la6fgg3icmrqeus524th3kv1uf59ri97.apps.googleusercontent.com',
    iosBundleId: 'com.bcsportsMobile.nftApplicaion',
  );
}
