// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtWmz0-dkS7_S43b01UH7sV0hwN1LhLZA',
    appId: '1:626741015:web:1dd9654c0c24b38b20b152',
    messagingSenderId: '626741015',
    projectId: 'bcsports-mobile',
    authDomain: 'bcsports-mobile.firebaseapp.com',
    storageBucket: 'bcsports-mobile.appspot.com',
    measurementId: 'G-YF4XX6TJBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkBZ6eRSGvpfH1DJBgRGHlSDwVfViXvAA',
    appId: '1:626741015:android:e521a32a674ca4d120b152',
    messagingSenderId: '626741015',
    projectId: 'bcsports-mobile',
    storageBucket: 'bcsports-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Ni7eCvOjwPRFK-8W_rml9dxERkNjv-8',
    appId: '1:626741015:ios:e0baf9381c21410e20b152',
    messagingSenderId: '626741015',
    projectId: 'bcsports-mobile',
    storageBucket: 'bcsports-mobile.appspot.com',
    iosBundleId: 'com.example.bcsportsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Ni7eCvOjwPRFK-8W_rml9dxERkNjv-8',
    appId: '1:626741015:ios:5ec851ab8f857e8220b152',
    messagingSenderId: '626741015',
    projectId: 'bcsports-mobile',
    storageBucket: 'bcsports-mobile.appspot.com',
    iosBundleId: 'com.example.bcsportsMobile.RunnerTests',
  );
}
